Host = '127.0.0.1:5000'

# 上傳檔案體積上限，單位: MB
UploadLimit = 50

# 明文密码
Password = 'abcd'

# 最近檔案數量（第一頁檔案數量上限）
RecentFilesLimit = 100

# 舊文字檔案木數量上限
OldTextFilesLimit = 100

# 嘗試密碼的頻率限制（次/分鐘）
# https://docs.gofiber.io/api/middleware/limiter
RepeatRequestLimit = 5
